version: "3.8"

services:

  web:
    build: ./
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    env_file:
      ./.env

  db:
    image: postgres:15.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

  redis:
    image: redis:7.0.5
    restart: always
    ports:
      - 6379:6379

volumes:
  postgres_data: